server:
  port: 5959

spring:
  profiles:
    active: test
  batch:
    job:
      names: ${job.name:NONE}
  main:
    allow-bean-definition-overriding: true
  quartz:
    scheduler-name: MyScheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    overwrite-existing-jobs: true
logging.level.org.springframework.batch: DEBUG





---

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: h2
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/begin
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
  config:
    activate:
      on-profile: test
